{"name": "test_practicechapters", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: MicrosoftEdge=117.0.2045.35)\nStacktrace:\n0   msedgedriver                        0x0000000104fb3a10 msedgedriver + 4160016\n1   msedgedriver                        0x0000000104fabad0 msedgedriver + 4127440\n2   msedgedriver                        0x0000000104bf5338 msedgedriver + 234296\n3   msedgedriver                        0x0000000104be4d4c msedgedriver + 167244\n4   msedgedriver                        0x0000000104be4a64 msedgedriver + 166500\n5   msedgedriver                        0x0000000104c59428 msedgedriver + 644136\n6   msedgedriver                        0x0000000104c24d04 msedgedriver + 429316\n7   msedgedriver                        0x0000000104c25bb8 msedgedriver + 433080\n8   msedgedriver                        0x0000000104f82070 msedgedriver + 3956848\n9   msedgedriver                        0x0000000104f856cc msedgedriver + 3970764\n10  msedgedriver                        0x0000000104f851bc msedgedriver + 3969468\n11  msedgedriver                        0x0000000104f8a500 msedgedriver + 3990784\n12  msedgedriver                        0x0000000104f85d7c msedgedriver + 3972476\n13  msedgedriver                        0x0000000104f6861c msedgedriver + 3851804\n14  msedgedriver                        0x0000000104f9d47c msedgedriver + 4068476\n15  msedgedriver                        0x0000000104f9d5a8 msedgedriver + 4068776\n16  msedgedriver                        0x0000000104faad5c msedgedriver + 4123996\n17  libsystem_pthread.dylib             0x000000018b0fef94 _pthread_start + 136\n18  libsystem_pthread.dylib             0x000000018b0f9d34 thread_start + 8", "trace": "self = <Test.test_E2E.TestEmbibe object at 0x103979f90>\n\n    @pytest.mark.usefixtures(\"setup\", \"log_on_failure\")\n    @pytest.mark.practice\n    def test_practicechapters(self):\n        log = self.getLogger()\n        self.test_sign_in_password()\n        ph = PracticeHomePage(self.driver)\n        log.info(\"Test case: Clicking on Practice Chapter in Practice Home\")\n        log.info(\"Test case: Practice Now Button is displayed in the Practice Summary\")\n        log.info(\"Test case: User is navigated to Practice Taking Screen on clicking on Practice Now button\")\n>       ph.practice_chapters()\n\nTest/test_E2E.py:262: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPageObject/practice_home_page.py:46: in practice_chapters\n    self.practice_taking()\nPageObject/practice_home_page.py:86: in practice_taking\n    if question_element.is_displayed():\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:252: in is_displayed\n    return self.parent.execute_script(f\"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);\", self)\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:414: in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x103c5ca50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"disconnected\",\"message\":\"disconnected: not connected to DevTools\\\\n  (fai...00018b0fef94 _pthread_start + 136\\\\n18  libsystem_pthread.dylib             0x000000018b0f9d34 thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\nE         (failed to check if window was closed: disconnected: not connected to DevTools)\nE         (Session info: MicrosoftEdge=117.0.2045.35)\nE       Stacktrace:\nE       0   msedgedriver                        0x0000000104fb3a10 msedgedriver + 4160016\nE       1   msedgedriver                        0x0000000104fabad0 msedgedriver + 4127440\nE       2   msedgedriver                        0x0000000104bf5338 msedgedriver + 234296\nE       3   msedgedriver                        0x0000000104be4d4c msedgedriver + 167244\nE       4   msedgedriver                        0x0000000104be4a64 msedgedriver + 166500\nE       5   msedgedriver                        0x0000000104c59428 msedgedriver + 644136\nE       6   msedgedriver                        0x0000000104c24d04 msedgedriver + 429316\nE       7   msedgedriver                        0x0000000104c25bb8 msedgedriver + 433080\nE       8   msedgedriver                        0x0000000104f82070 msedgedriver + 3956848\nE       9   msedgedriver                        0x0000000104f856cc msedgedriver + 3970764\nE       10  msedgedriver                        0x0000000104f851bc msedgedriver + 3969468\nE       11  msedgedriver                        0x0000000104f8a500 msedgedriver + 3990784\nE       12  msedgedriver                        0x0000000104f85d7c msedgedriver + 3972476\nE       13  msedgedriver                        0x0000000104f6861c msedgedriver + 3851804\nE       14  msedgedriver                        0x0000000104f9d47c msedgedriver + 4068476\nE       15  msedgedriver                        0x0000000104f9d5a8 msedgedriver + 4068776\nE       16  msedgedriver                        0x0000000104faad5c msedgedriver + 4123996\nE       17  libsystem_pthread.dylib             0x000000018b0fef94 _pthread_start + 136\nE       18  libsystem_pthread.dylib             0x000000018b0f9d34 thread_start + 8\n\n../../.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException"}, "attachments": [{"name": "log", "source": "f1c880d6-6c87-462e-90cc-c06752bc8bc6-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3bc44308-1b6e-46ba-b161-cdbf4537aa0d-attachment.txt", "type": "text/plain"}], "start": 1747732331729, "stop": 1747732348751, "uuid": "377a5c91-c189-4f7e-a32f-386f8d4ee0b6", "historyId": "356cea6b869cf85fa95b6af8175455d3", "testCaseId": "356cea6b869cf85fa95b6af8175455d3", "fullName": "Test.test_E2E.TestEmbibe#test_practicechapters", "labels": [{"name": "tag", "value": "practice"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_E2E"}, {"name": "subSuite", "value": "TestEmbibe"}, {"name": "host", "value": "LM0010069"}, {"name": "thread", "value": "8101-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_E2E"}]}