{"uuid": "76c3f6b1-e80a-4f40-af5a-98ca9b7f3b7b", "children": ["0e21c23d-d9fa-4e4c-b441-6d195664b559"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1736499958424, "stop": 1736499958424}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.265)\nStacktrace:\n0   chromedriver                        0x0000000101302138 cxxbridge1$str$ptr + 3653888\n1   chromedriver                        0x00000001012fa988 cxxbridge1$str$ptr + 3623248\n2   chromedriver                        0x0000000100d60968 cxxbridge1$string$len + 89228\n3   chromedriver                        0x0000000100d3be44 core::str::slice_error_fail::ha0e52dbcb60e6bae + 3780\n4   chromedriver                        0x0000000100dcac84 cxxbridge1$string$len + 524200\n5   chromedriver                        0x0000000100dddb60 cxxbridge1$string$len + 601732\n6   chromedriver                        0x0000000100d99564 cxxbridge1$string$len + 321672\n7   chromedriver                        0x0000000100d9a1b4 cxxbridge1$string$len + 324824\n8   chromedriver                        0x00000001012ccfc0 cxxbridge1$str$ptr + 3436424\n9   chromedriver                        0x00000001012d02dc cxxbridge1$str$ptr + 3449508\n10  chromedriver                        0x00000001012b3e60 cxxbridge1$str$ptr + 3333672\n11  chromedriver                        0x00000001012d0b9c cxxbridge1$str$ptr + 3451748\n12  chromedriver                        0x00000001012a5678 cxxbridge1$str$ptr + 3274304\n13  chromedriver                        0x00000001012eb2b4 cxxbridge1$str$ptr + 3560060\n14  chromedriver                        0x00000001012eb430 cxxbridge1$str$ptr + 3560440\n15  chromedriver                        0x00000001012fa5fc cxxbridge1$str$ptr + 3622340\n16  libsystem_pthread.dylib             0x000000019fe02f94 _pthread_start + 136\n17  libsystem_pthread.dylib             0x000000019fdfdd34 thread_start + 8\n\n", "trace": "  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/Student-App-Web/Test/conftest.py\", line 63, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1736499986936, "stop": 1736499986942}], "start": 1736499958424, "stop": 1736499986942}